const developerData = {
    gcnit: {
        id: 'gcnit',
        linkedin_id: 'gcnit',
        codechef_id: 'gc_nit',
        twitter_id: 'gc_nit',
        medium_id: 'gc_nit',
        avatar_url: 'https://avatars.githubusercontent.com/u/4833751?v=4',
        name: 'Gaurav Chandak',
        company: 'workat.tech',
        blog: 'https://workat.tech',
        location: 'Bangalore, India',
        email: null,
        bio: 'Building workat.tech;\r\n' + 'Previously Software Engineer at  @Flipkart, @microsoft and @tracxn',
        github_id: 'gcnit',
        repos: [
            {
                name: 'awesome-learn-to-code',
                html_url: 'https://github.com/gcnit',
                description: 'A list of awesome resources for learning to code',
                updated_at: '2021-03-11T04:24:18Z',
            },
            {
                name: 'beta.sdeskills.com',
                html_url: 'https://github.com/gcnit',
                description: 'Beta SDE Skills site',
                updated_at: '2020-06-08T08:19:59Z',
            },
            {
                name: 'Birthdpy',
                html_url: 'https://github.com/gcnit',
                description:
                    'This script thanks everyone who have wished you on your birthday on your facebook timeline',
                updated_at: '2017-10-11T04:05:01Z',
            },
            {
                name: 'code-template',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2021-05-07T12:07:18Z',
            },
            {
                name: 'Comment-Liker',
                html_url: 'https://github.com/gcnit',
                description:
                    'Placed? Everyone congratulating you on your status update? Like all their comments automatically with this script!',
                updated_at: '2014-10-25T19:41:51Z',
            },
            {
                name: 'Competitive-Programming',
                html_url: 'https://github.com/gcnit',
                description: 'My solutions to algorithmic problems on Competitive Programming websites',
                updated_at: '2020-12-19T15:23:40Z',
            },
            {
                name: 'Competitive-Programming-Resources',
                html_url: 'https://github.com/gcnit',
                description: 'Competitive Programming & System Design Resources.',
                updated_at: '2021-05-23T13:45:33Z',
            },
            {
                name: 'conclave',
                html_url: 'https://github.com/gcnit',
                description: 'CRDT and WebRTC based real-time, peer-to-peer, collaborative text editor',
                updated_at: '2020-04-07T18:40:56Z',
            },
            {
                name: 'design-patterns-for-humans',
                html_url: 'https://github.com/gcnit',
                description: 'An ultra-simplified explanation to design patterns',
                updated_at: '2019-09-05T16:46:52Z',
            },
            {
                name: 'Design-Patterns-Implementation',
                html_url: 'https://github.com/gcnit',
                description: 'Implementations of Common Design Patterns',
                updated_at: '2017-11-26T07:35:43Z',
            },
            {
                name: 'developer-roadmap',
                html_url: 'https://github.com/gcnit',
                description: 'Roadmap to becoming a web developer in 2018',
                updated_at: '2019-01-30T06:24:48Z',
            },
            {
                name: 'gcnit',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2020-08-15T20:31:18Z',
            },
            {
                name: 'gcnit.github.io',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2019-11-12T16:52:28Z',
            },
            {
                name: 'get-a-software-engineering-job',
                html_url: 'https://github.com/gcnit',
                description: 'Get a Software Engineering Job - Ultimate Guide',
                updated_at: '2020-08-16T10:53:19Z',
            },
            {
                name: 'Implementations',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2017-11-22T17:36:47Z',
            },
            {
                name: 'learn-to-program',
                html_url: 'https://github.com/gcnit',
                description: 'Educational resources to learn to program (Foundation in Web Development)',
                updated_at: '2020-08-12T18:28:02Z',
            },
            {
                name: 'learn_to_code',
                html_url: 'https://github.com/gcnit',
                description: 'Resources for budding developers',
                updated_at: '2020-08-12T18:30:07Z',
            },
            {
                name: 'Like-All-Posts',
                html_url: 'https://github.com/gcnit',
                description: 'This script likes all the posts made by an user or a page on their facebook timeline',
                updated_at: '2016-08-07T05:48:03Z',
            },
            {
                name: 'low-level-design',
                html_url: 'https://github.com/gcnit',
                description: 'This repository contains some programs for learning OOD using c++',
                updated_at: '2021-06-04T18:01:24Z',
            },
            {
                name: 'low-level-design-primer',
                html_url: 'https://github.com/gcnit',
                description:
                    'Dedicated Resources for the Low-Level System Design. Learn how to design and implement large-scale systems. Prep for the system design interview.',
                updated_at: '2021-04-27T19:44:55Z',
            },
            {
                name: 'machinecoding',
                html_url: 'https://github.com/gcnit',
                description: 'Everything about Machine Coding Round',
                updated_at: '2020-03-03T18:31:32Z',
            },
            {
                name: 'mediumish-minimal',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2020-03-08T12:34:41Z',
            },
            {
                name: 'mentorship-karona',
                html_url: 'https://github.com/gcnit',
                description: 'If you need a session with mentors raise an issue',
                updated_at: '2020-08-31T21:28:33Z',
            },
            {
                name: 'Mind-Expanding-Books',
                html_url: 'https://github.com/gcnit',
                description: ' :books: Books that will blow your mind ',
                updated_at: '2019-01-30T06:24:59Z',
            },
            {
                name: 'mock-machine-coding-1',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2021-05-30T13:10:49Z',
            },
            {
                name: 'NITMDb',
                html_url: 'https://github.com/gcnit',
                description: 'A script that helps you get your movie collection sorted based on their IMDb ratings',
                updated_at: '2018-05-26T09:25:37Z',
            },
            {
                name: 'pdfkit-invoice',
                html_url: 'https://github.com/gcnit',
                description: 'Generate PDF Invoices with PDFKit',
                updated_at: '2020-08-14T11:02:56Z',
            },
            {
                name: 'problemsolving',
                html_url: 'https://github.com/gcnit',
                description: 'Everything about the Problem Solving & Data Structures Round',
                updated_at: '2020-03-12T20:49:45Z',
            },
            {
                name: 'product-search',
                html_url: 'https://github.com/gcnit',
                description: null,
                updated_at: '2020-02-02T08:52:35Z',
            },
            {
                name: 'programming-principles',
                html_url: 'https://github.com/gcnit',
                description: 'Categorized overview of Programming Principles & Patterns',
                updated_at: '2019-01-30T06:24:57Z',
            },
        ],
    },
    'anmol-joshi': {
        id: 'anmol-joshi',
        // linkedin_id: 'gcnit',
        // codechef_id: 'gc_nit',
        // twitter_id: 'gc_nit',
        // medium_id: 'gc_nit',
        avatar_url: 'https://avatars.githubusercontent.com/u/46377877?v=4',
        name: 'Anmol Joshi',
        company: null,
        blog: 'https://www.linkedin.com/in/anmol-joshi/',
        location: null,
        email: null,
        bio: null,
        github_id: 'Anmol-Joshi',
        repos: [
            {
                name: 'Blog-website',
                html_url: 'https://github.com/Anmol-Joshi',
                description: 'Blog-website from AY challenge ',
                updated_at: '2021-02-27T06:37:26Z',
            },
            {
                name: 'boilerplate-npm',
                html_url: 'https://github.com/Anmol-Joshi',
                description: 'A boilerplate for the freeCodeCamp curriculum.',
                updated_at: '2021-02-16T14:17:35Z',
            },
            {
                name: 'flashtype',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-03-14T13:31:12Z',
            },
            {
                name: 'flask-postgres-app',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-03-25T07:13:58Z',
            },
            {
                name: 'flask-rest-api',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-03-18T15:44:58Z',
            },
            {
                name: 'nameit',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-03-03T11:16:06Z',
            },
            {
                name: 'PlacmentPrepGuide',
                html_url: 'https://github.com/Anmol-Joshi',
                description: 'Includes all the resources for Core CS fundamentals',
                updated_at: '2021-03-24T09:55:03Z',
            },
            {
                name: 'portfolio-site',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-05-25T16:20:05Z',
            },
            {
                name: 'Quiz-Application',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-04-26T02:52:27Z',
            },
            {
                name: 'random_csv_generator',
                html_url: 'https://github.com/Anmol-Joshi',
                description: 'Tool for rendering plausible real-life csv data.',
                updated_at: '2021-02-18T08:35:17Z',
            },
            {
                name: 'ToDoList',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-02-21T04:01:23Z',
            },
            {
                name: 'url-shortner',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-06-05T17:37:36Z',
            },
            {
                name: 'Utility-Application',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-05-13T08:35:17Z',
            },
            {
                name: 'utility-applications',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-06-01T02:02:39Z',
            },
            {
                name: 'VanillaJSProjects',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-04-01T14:02:16Z',
            },
            {
                name: 'WebSocket-ChatApp',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-02-25T10:28:34Z',
            },
            {
                name: 'workattech-component-library',
                html_url: 'https://github.com/Anmol-Joshi',
                description: null,
                updated_at: '2021-05-06T17:57:34Z',
            },
        ],
    },
};
module.exports = developerData;
